version: '3.2'

services:
  app:
    build: ./backend
    container_name: chat_backend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks: 
      - app_net
    command: npm start
    restart: always
    links:
      - mysql:db
      - redis:redis
    volumes: 
      - type: bind
        source: ./backend
        target: /usr/src/app
  frontend: 
    build: ./frontend
    restart: always
    container_name: chat_frontend
    ports:
      - 8080:80
    links:
      - app:backend
  redis:
    build: ./redis
    restart: always
    volumes: 
      - type: bind
        source: ./redis/data
        target: /data
    ports:
      - 6379:6379
    networks: 
      - app_net
  mysql:
    build: ./mysql
    container_name: chat_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zxcds12#12
    volumes: 
      - type: bind
        source: ./mysql/data
        target: /var/lib/mysql
    ports: 
      - 3306:3306
    networks: 
      - app_net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chat_myadmin
    restart: always
    ports:
      - 8090:80
    links:
      - mysql:db
    networks:
      - app_net

networks: 
  app_net:
    driver: bridge
