version: '3.2'

services:
  app:
    build: ./backend
    container_name: chat_backend
    restart: always
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    networks: 
      - app_net
    command: npm run debug
    volumes: 
      - type: bind
        source: ./backend
        target: /usr/src/app

networks: 
  app_net:
    driver: bridge
